### ISSUE TITLE
UrlConnectionClient.java line 71

### ISSUE THREAD

**Issue by thunsaker** [thunsaker/soup#85]
#### in retrofit.client.UrlConnectionClient.readResponse
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/thomas-hunsaker/android/apps/com.thunsaker.soup/issues/5425b78de3de5099baec4b9d](https://crashlytics.com/thomas-hunsaker/android/apps/com.thunsaker.soup/issues/5425b78de3de5099baec4b9d)

**Comment by thunsaker** [comment]
api.forusquare.com was down?
According to status.foursquare.com, they were not down...

```
Caused by: retrofit.RetrofitError: java.net.UnknownHostException: Unable to resolve host "api.foursquare.com": No address associated with hostname
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:385)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:241)
       at $Proxy0.getUserInfo()
       at com.thunsaker.soup.services.foursquare.FoursquareTasks$GetUserInfo.doInBackground(FoursquareTasks.java:720)
       at com.thunsaker.soup.services.foursquare.FoursquareTasks$GetUserInfo.doInBackground(FoursquareTasks.java:706)
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
```

Closing, if this pops up again, I'll take a nother look.
