### ISSUE TITLE
VenueSearchActivity.java line 92

### ISSUE THREAD

**Issue by thunsaker** [thunsaker/soup#89]
#### in com.thunsaker.soup.ui.VenueSearchActivity.onCreate
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://crashlytics.com/thomas-hunsaker/android/apps/com.thunsaker.soup/issues/54267b57e3de5099baed4f94](https://crashlytics.com/thomas-hunsaker/android/apps/com.thunsaker.soup/issues/54267b57e3de5099baed4f94)

**Comment by thunsaker** [comment]
Didn't like my custom progress bar...
Android 4.0.4

```
java.lang.OutOfMemoryError
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:490)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:358)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:773)
       at android.content.res.Resources.loadDrawable(Resources.java:1935)
       at android.content.res.Resources.getDrawable(Resources.java:664)
       at android.graphics.drawable.AnimationDrawable.inflate(AnimationDrawable.java:280)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:867)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:804)
       at android.content.res.Resources.loadDrawable(Resources.java:1920)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
       at android.widget.ProgressBar.<init>(ProgressBar.java:287)
       at com.android.internal.widget.ActionBarView.initProgress(ActionBarView.java:300)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2845)
       at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:266)
       at android.app.Activity.setContentView(Activity.java:1835)
       at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:216)
       at android.support.v7.app.ActionBarActivityDelegateICS.setContentView(ActionBarActivityDelegateICS.java:110)
       at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:76)
       at com.thunsaker.soup.ui.VenueSearchActivity.onCreate(VenueSearchActivity.java:92)
       at android.app.Activity.performCreate(Activity.java:4465)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
       at android.app.ActivityThread.access$600(ActivityThread.java:127)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4441)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
